---
title: "imputation_lab"
author: "Tjardo M"
date: "4/1/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd('/exports/reum/tdmaarseveen/RA_Clustering')
# Set library folder
.libPaths("/exports/reum/tdmaarseveen/Rlibs")
```
```{r}
#install.packages("tidyverse")
```


## Import Lab data

```{r}
library(readr)
df_lab <- read_delim("../../data/3_wide/DF_Lab_wide_Missingness.csv", "|", escape_double = FALSE, trim_ws = TRUE)
head(df_lab)
```

## Visualize missingness

```{r}
#library("tidyverse")
source('../../src/2_imputation_steps/functions-for-imputation.R')
plot_missing(df_lab, "LAB")
```


```{r}
colnames(df_lab) <- c("patnr","time","MCV", "Ht","Leuko", "MCHC", "MCH",  "BSE", "Hb", "Trom", "Mono", "Lymf", "ALP", "CRP", "RF", "aCCP", "aSSA", "ENA", "ANA")

# Make subset
df_sub <- subset(df_lab, select=c("patnr", "time","MCV","Leuko", "MCH", "Hb", "aSSA", "ANA", "aCCP", "Ht", "MCHC", "BSE", "Trom", "ENA", "RF"))
```

```{r}
colnames(df_lab)
```


```{r}
# str2lang -> crashes if you have special characters

pred <- make_prediction_matrix(df_sub)
## Create prediction matrix - make patient id non predictive
pred$patnr <- 0
pred$time <- 0
#pred$Months.since.1st.Visit <- 0
```

```{r}
## Record time of running, and do the actual imputation
# data, iterations, number of imputations and predictionmatrix
data_imp <- do_imputation(df_sub, 20, 30, pred)
```

```{r}
after_imp_plots(data_imp, "LAB")
```
```{r}
## extra plots because there are so many columns that the regular one doesn't fit
pdf(file = "LAB_density.pdf")
densityplot( x=data_imp )
dev.off() # , data= ~ DAS_28_CRP_BL+DAS_28_CRP_6mo+DAS_28_CRP_12mo
```
## Check mean of original vs imputed
```{r}
# step 9:
## copy of the original, and complete the new
original <- df_sub
imp_df <- complete(data_imp)
write.csv(imp_df, '../../data/4_imputed/DF_Lab_imputed.csv')

# step 10:
## check the mean of the completed, and original dataset
summary(original$BSE)
summary(imp_df$BSE)

quantile(original$BSE, na.rm=T)
quantile(imp_df$BSE, na.rm=T)
#

```

## Look at boxplot of original vs imputed

```{r}

make_boxplot("LAB_BSE", original, imp_df, "BSE")
```


## Ref: Perform data imputation with MICE

link: datascienceplus.com/imputing-missing-data-with-r-mice-package/
original study: Multivariate Imputation by Chained Equations (www.jstatsoft.org/article/view/v045i03)



